version: "3"
services:
  search-api:
    build: ./golang-api/
    ports:
      - "8080:8080"
    networks:
      - app_net
    restart: on-failure
    depends_on:
      - postgres-server
    environment:
     - mode=startPG
    command: ["/go/bin/golang-api"]
  search-web:
    build: ./html-web-ui/
    ports:
      - "8000:8000"
    networks:
      - app_net
    depends_on:
      - search-api
  postgres-server:
    build: ./postgres/
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - "DATABASE=voucher_db"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge